### ISSUE TITLE
[WARNING]your gpu arch (8, 9) isn't compiled in prebuilt, may cause invalid device function. available: {(7, 0), (6, 1), (8, 0), (6, 0), (7, 5), (8, 6), (5, 2)}

### ISSUE THREAD

**Issue by rasrab1992** [robot-learning-freiburg/PADLoC#2]
Hello,

Thank you for your good work. I've encountered an [Warning] while attempting to train the model with my RTX 4090 GPUs. The [Warning] message indicates that the GPU architecture (8, 9) is not compiled in the prebuilt version, which might lead to invalid device functions. The supported architectures listed are {(7, 0), (6, 1), (8, 0), (6, 0), (7, 5), (8, 6), (5, 2)}. I suspect this discrepancy is due to the newer architecture of my GPUs.

I am using the Docker version provided, and I'm considering adjusting the CUDA version or other relevant libraries to address this issue. Could you please specify the CUDA versions with which your code are compatible? This information will guide me in ensuring a smooth integration with my RTX 4090 GPUs. Thank you for your assistance.

**Comment by yuxuanfanOrion** [comment]
I meet the same warning. Have you solved it?

**Comment by ysssssha** [comment]
I got the same warning. In my case, the result was quite bad with the warning. Did it affect to the result?
Please inform us how to solve the problem.
Thank you

**Comment by alexjunholee** [comment]
If the performance is not showing a problem, you can just suppress them from your locally installed path, e.g. ``${HOME}/.local/lib/python3.9/site-packages/spconv/pytorch/cppcore.py``

The warning prints from line 61 of ``spconv/pytorch/cppcore.py``.
